### ISSUE TITLE
move go sdk to a separate repository

### ISSUE THREAD

**Issue by tifayuki** [capitalonline/terraform-provider-cds#6]
把go的sdk放到单独的github repo里，作为公用的库，后续有其他的项目依赖该sdk

**Comment by nevermosby** [comment]
+1, I have created a project, https://github.com/nevermosby/gic-cli-tool, to build a command line tool for cds resource managing. It will help if there is a CDS-SDK repo to integrate with.

**Comment by tifayuki** [comment]
moved SDK to https://github.com/capitalonline/cds-gic-sdk-go

@nevermosby  you can send your CLI PR to the following repo: https://github.com/capitalonline/cds-gic-cli
